### ISSUE TITLE
FR: Show 'marked as read' on listing page as well

### ISSUE THREAD

**Issue by trip41** [edoreld/mark-as-read#3]
I would find it extremely useful to extend this idea to the listing page as well -- displaying the ticks for list items that I've 'marked as read' so as I'm looking through a list of apartment listings I already know from the list item which ones I've already seen.

I'm thinking this can be done by scanning the DOM for an element that contains the link to the pages that I've marked as read and insert a checkbox icon into the page, positioning it next to it, or maybe change it's background color or something.

I'm happy to fork+contribute. Curious to have your thoughts.

**Comment by edoreld** [comment]
I think this would be a fantastic addition to the add-on and infinitely more useful. I'm currently not actively developing this extension, but will definitely would accept pull requests that added this kind of functionality. 

The only problem with this approach is that there might be several links pointing to the same URL. In this case, the addon would show several checkmarks instead of just one, which would be suboptimal imho. 

There's also an option to add a right-click "mark as read" action that would apply the checkmark to whichever element was clicked on. This could be useful especially on images such as those of apartment listings.

**Comment by edoreld** [comment]
Implemented in https://github.com/edoreld/mark-as-read/pull/4
